inherit_from: .rubocop_todo.yml

AllCops:
  # Include:
  #   - Gemfile
  #   - Rakefile
  #   - lib/
  #   - spec/
  Exclude:
    - renc.gemspec
    - vendor/**/*
    - bin/**/*

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
