language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 2.0.0
# before_install:
#   - gem update --system --no-doc
#   - gem install bundler
# after_success:
#   - bundle exec codeclimate-test-reporter
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
# script:
#   - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
