language: ruby
cache: bundler
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
  - 2.0.0
before_install:
  - gem update --system --no-doc
  - gem install bundler
after_success:
  - bundle exec codeclimate-test-reporter
